export const translations = {
  en: {
    openFiles: "Open File", openPng: "Open PNG", openCtex: "Open CTEX", clearFile: "Clear File", dropFiles: "Drop PNG or CTEX", fileName: "Name", format: "Format", fileSize: "Size", resolution: "Resolution", export: "Export File", exportPng: "Export PNG", exportCtex: "Export CTEX", zoomIn: "Zoom in", zoomOut: "Zoom out",
    start: "Open a PNG or supported CTEX file to begin.", pngOnly: "Only PNG files can be opened.", pngRead: "Unable to read the PNG image.", opened: "{name} opened.", cleared: "File cleared.", fileTooSmall: "The file is too small.", notGst2: "This is not a GST2 CTEX file.", unsupportedVersion: "Unsupported CTEX version.", unsupportedCtex: "This is not a WebP-based CTEX file. S3TC and BPTC CTEX are not supported in v0.6.", invalidResolution: "The CTEX resolution header is invalid.", unsupportedPixelFormat: "Unsupported WebP CTEX pixel format.", invalidPayloadLength: "The CTEX WebP payload length does not match.", invalidWebp: "The CTEX does not contain a valid RIFF/WebP payload.", mismatchedResolution: "The CTEX header and embedded WebP resolution do not match.", webpRead: "Unable to read the embedded WebP image.", pngExported: "PNG exported.", ctexExported: "CTEX exported.", exportFailed: "Unable to export the image.", dimensionLimit: "CTEX export currently supports dimensions up to 65,535px.", webpCreateFailed: "The browser did not create a valid WebP image.", imageCreateFailed: "Unable to create the image."
  },
  ko: {
    openFiles: "파일 열기", openPng: "PNG 열기", openCtex: "CTEX 열기", clearFile: "파일 제거", dropFiles: "PNG 또는 CTEX 파일 놓기", fileName: "이름", format: "형식", fileSize: "크기", resolution: "해상도", export: "파일 내보내기", exportPng: "PNG 내보내기", exportCtex: "CTEX 내보내기", zoomIn: "확대", zoomOut: "축소",
    start: "PNG 또는 지원되는 CTEX 파일을 열어 시작하세요.", pngOnly: "PNG 파일만 열 수 있습니다.", pngRead: "PNG 이미지를 읽을 수 없습니다.", opened: "{name}을(를) 열었습니다.", cleared: "파일을 제거했습니다.", fileTooSmall: "파일이 너무 작습니다.", notGst2: "GST2 CTEX 파일이 아닙니다.", unsupportedVersion: "지원하지 않는 CTEX 버전입니다.", unsupportedCtex: "이 CTEX는 WebP 기반 일반 형식이 아닙니다. S3TC·BPTC CTEX는 v0.6에서 지원하지 않습니다.", invalidResolution: "CTEX 해상도 헤더가 유효하지 않습니다.", unsupportedPixelFormat: "지원하지 않는 WebP CTEX 픽셀 형식입니다.", invalidPayloadLength: "CTEX WebP 페이로드 길이가 일치하지 않습니다.", invalidWebp: "CTEX에 유효한 RIFF/WebP 페이로드가 없습니다.", mismatchedResolution: "CTEX 헤더와 내부 WebP의 해상도가 일치하지 않습니다.", webpRead: "내부 WebP 이미지를 읽을 수 없습니다.", pngExported: "PNG를 내보냈습니다.", ctexExported: "CTEX를 내보냈습니다.", exportFailed: "이미지를 내보낼 수 없습니다.", dimensionLimit: "CTEX는 현재 65,535px 이하의 너비와 높이만 내보낼 수 있습니다.", webpCreateFailed: "브라우저가 유효한 WebP를 생성하지 못했습니다.", imageCreateFailed: "이미지를 생성할 수 없습니다."
  },
  ja: {
    openFiles: "ファイルを開く", openPng: "PNGを開く", openCtex: "CTEXを開く", clearFile: "ファイルをクリア", dropFiles: "PNG または CTEX をドロップ", fileName: "名前", format: "形式", fileSize: "サイズ", resolution: "解像度", export: "ファイルを書き出す", exportPng: "PNGを書き出す", exportCtex: "CTEXを書き出す", zoomIn: "拡大", zoomOut: "縮小",
    start: "PNG または対応する CTEX ファイルを開いてください。", pngOnly: "PNG ファイルのみ開けます。", pngRead: "PNG 画像を読み込めません。", opened: "{name} を開きました。", cleared: "ファイルをクリアしました。", fileTooSmall: "ファイルが小さすぎます。", notGst2: "GST2 CTEX ファイルではありません。", unsupportedVersion: "対応していない CTEX バージョンです。", unsupportedCtex: "この CTEX は WebP ベースの標準形式ではありません。S3TC・BPTC CTEX は v0.6 では未対応です。", invalidResolution: "CTEX の画像サイズヘッダーが無効です。", unsupportedPixelFormat: "対応していない WebP CTEX ピクセル形式です。", invalidPayloadLength: "CTEX WebP ペイロードの長さが一致しません。", invalidWebp: "CTEX に有効な RIFF/WebP ペイロードがありません。", mismatchedResolution: "CTEX ヘッダーと内部 WebP の画像サイズが一致しません。", webpRead: "内部 WebP 画像を読み込めません。", pngExported: "PNG を書き出しました。", ctexExported: "CTEX を書き出しました。", exportFailed: "画像を書き出せません。", dimensionLimit: "CTEX の書き出しは現在、幅と高さが 65,535px 以下の場合に対応しています。", webpCreateFailed: "ブラウザが有効な WebP を生成できませんでした。", imageCreateFailed: "画像を生成できません。"
  },
  "zh-CN": {
    openFiles: "打开文件", openPng: "打开 PNG", openCtex: "打开 CTEX", clearFile: "清除文件", dropFiles: "拖放 PNG 或 CTEX", fileName: "名称", format: "格式", fileSize: "大小", resolution: "分辨率", export: "导出文件", exportPng: "导出 PNG", exportCtex: "导出 CTEX", zoomIn: "放大", zoomOut: "缩小",
    start: "打开 PNG 或受支持的 CTEX 文件以开始。", pngOnly: "只能打开 PNG 文件。", pngRead: "无法读取 PNG 图像。", opened: "已打开 {name}。", cleared: "已清除文件。", fileTooSmall: "文件过小。", notGst2: "这不是 GST2 CTEX 文件。", unsupportedVersion: "不支持的 CTEX 版本。", unsupportedCtex: "此 CTEX 不是基于 WebP 的标准格式。v0.6 暂不支持 S3TC 和 BPTC CTEX。", invalidResolution: "CTEX 分辨率头无效。", unsupportedPixelFormat: "不支持的 WebP CTEX 像素格式。", invalidPayloadLength: "CTEX WebP 有效负载长度不匹配。", invalidWebp: "CTEX 不包含有效的 RIFF/WebP 有效负载。", mismatchedResolution: "CTEX 头与内嵌 WebP 的分辨率不一致。", webpRead: "无法读取内嵌的 WebP 图像。", pngExported: "已导出 PNG。", ctexExported: "已导出 CTEX。", exportFailed: "无法导出图像。", dimensionLimit: "目前 CTEX 导出仅支持宽度和高度不超过 65,535px 的图像。", webpCreateFailed: "浏览器未能创建有效的 WebP 图像。", imageCreateFailed: "无法创建图像。"
  }
};
