export const translations = {
  en: {
    openFiles: "Open File", openPng: "Open PNG", openJpg: "Open JPG", openCtex: "Open CTEX", clearFile: "Clear File", dropFiles: "Drop a file", fileName: "Name", format: "Format", fileSize: "Size", resolution: "Resolution", export: "Export File", exportPng: "Export PNG", exportJpg: "Export JPG", exportCtex: "Export CTEX", jpgBackground: "JPG Background", backgroundWhite: "White", backgroundGray: "Gray", backgroundBlack: "Black", backgroundCustom: "Custom", autoFit: "Auto-fit Preview", themeLight: "Switch to light mode", themeDark: "Switch to dark mode", rotateLeft: "Rotate left", rotateRight: "Rotate right", flipHorizontal: "Flip horizontal", flipVertical: "Flip vertical", zoomIn: "Zoom in", zoomOut: "Zoom out",
    start: "Open a PNG, JPG, or supported CTEX file to begin.", opened: "{name} opened.", cleared: "File cleared.", rotatedLeft: "Image rotated left.", rotatedRight: "Image rotated right.", flippedHorizontal: "Image flipped horizontally.", flippedVertical: "Image flipped vertically.", pngExported: "PNG exported.", jpgExported: "JPG exported.", ctexExported: "CTEX exported.", unsupportedFile: "Unsupported file format.", imageRead: "Unable to read the image.", unsupportedCtex: "Unsupported CTEX format.", ctexRead: "Unable to read the CTEX file.", dimensionLimit: "CTEX export supports dimensions up to 65,535px.", exportFailed: "Unable to export the file."
  },
  ko: {
    openFiles: "파일 열기", openPng: "PNG 열기", openJpg: "JPG 열기", openCtex: "CTEX 열기", clearFile: "파일 지우기", dropFiles: "파일 놓기", fileName: "이름", format: "형식", fileSize: "크기", resolution: "해상도", export: "파일 내보내기", exportPng: "PNG 내보내기", exportJpg: "JPG 내보내기", exportCtex: "CTEX 내보내기", jpgBackground: "JPG 배경색", backgroundWhite: "흰색", backgroundGray: "회색", backgroundBlack: "검정색", backgroundCustom: "사용자 지정", autoFit: "Preview 자동 맞춤", themeLight: "라이트 모드로 전환", themeDark: "다크 모드로 전환", rotateLeft: "왼쪽 회전", rotateRight: "오른쪽 회전", flipHorizontal: "좌우 반전", flipVertical: "상하 반전", zoomIn: "확대", zoomOut: "축소",
    start: "PNG, JPG 또는 지원되는 CTEX 파일을 열어 시작하세요.", opened: "{name} 파일을 열었습니다.", cleared: "파일을 지웠습니다.", rotatedLeft: "이미지를 왼쪽으로 회전했습니다.", rotatedRight: "이미지를 오른쪽으로 회전했습니다.", flippedHorizontal: "이미지를 좌우로 반전했습니다.", flippedVertical: "이미지를 상하로 반전했습니다.", pngExported: "PNG를 내보냈습니다.", jpgExported: "JPG를 내보냈습니다.", ctexExported: "CTEX를 내보냈습니다.", unsupportedFile: "지원하지 않는 파일 형식입니다.", imageRead: "이미지를 읽을 수 없습니다.", unsupportedCtex: "지원하지 않는 CTEX 형식입니다.", ctexRead: "CTEX 파일을 읽을 수 없습니다.", dimensionLimit: "CTEX 내보내기는 가로·세로 65,535px 이하만 지원합니다.", exportFailed: "파일을 내보낼 수 없습니다."
  },
  ja: {
    openFiles: "ファイルを開く", openPng: "PNGを開く", openJpg: "JPGを開く", openCtex: "CTEXを開く", clearFile: "ファイルを消去", dropFiles: "ファイルをドロップ", fileName: "名前", format: "形式", fileSize: "サイズ", resolution: "解像度", export: "ファイルを書き出す", exportPng: "PNGを書き出す", exportJpg: "JPGを書き出す", exportCtex: "CTEXを書き出す", jpgBackground: "JPG背景色", backgroundWhite: "白", backgroundGray: "グレー", backgroundBlack: "黒", backgroundCustom: "カスタム", autoFit: "プレビューを自動調整", themeLight: "ライトモードに切り替え", themeDark: "ダークモードに切り替え", rotateLeft: "左に回転", rotateRight: "右に回転", flipHorizontal: "左右反転", flipVertical: "上下反転", zoomIn: "拡大", zoomOut: "縮小",
    start: "PNG、JPG、または対応するCTEXファイルを開いてください。", opened: "{name} を開きました。", cleared: "ファイルを消去しました。", rotatedLeft: "画像を左に回転しました。", rotatedRight: "画像を右に回転しました。", flippedHorizontal: "画像を左右反転しました。", flippedVertical: "画像を上下反転しました。", pngExported: "PNGを書き出しました。", jpgExported: "JPGを書き出しました。", ctexExported: "CTEXを書き出しました。", unsupportedFile: "対応していないファイル形式です。", imageRead: "画像を読み込めません。", unsupportedCtex: "対応していないCTEX形式です。", ctexRead: "CTEXファイルを読み込めません。", dimensionLimit: "CTEXの書き出しは幅・高さ65,535px以下のみ対応しています。", exportFailed: "ファイルを書き出せません。"
  },
  "zh-CN": {
    openFiles: "打开文件", openPng: "打开 PNG", openJpg: "打开 JPG", openCtex: "打开 CTEX", clearFile: "清除文件", dropFiles: "拖放文件", fileName: "名称", format: "格式", fileSize: "大小", resolution: "分辨率", export: "导出文件", exportPng: "导出 PNG", exportJpg: "导出 JPG", exportCtex: "导出 CTEX", jpgBackground: "JPG 背景色", backgroundWhite: "白色", backgroundGray: "灰色", backgroundBlack: "黑色", backgroundCustom: "自定义", autoFit: "自动适应预览", themeLight: "切换到浅色模式", themeDark: "切换到深色模式", rotateLeft: "向左旋转", rotateRight: "向右旋转", flipHorizontal: "水平翻转", flipVertical: "垂直翻转", zoomIn: "放大", zoomOut: "缩小",
    start: "请打开 PNG、JPG 或受支持的 CTEX 文件。", opened: "已打开 {name}。", cleared: "已清除文件。", rotatedLeft: "图像已向左旋转。", rotatedRight: "图像已向右旋转。", flippedHorizontal: "图像已水平翻转。", flippedVertical: "图像已垂直翻转。", pngExported: "已导出 PNG。", jpgExported: "已导出 JPG。", ctexExported: "已导出 CTEX。", unsupportedFile: "不支持此文件格式。", imageRead: "无法读取图像。", unsupportedCtex: "不支持此 CTEX 格式。", ctexRead: "无法读取 CTEX 文件。", dimensionLimit: "CTEX 导出仅支持宽度和高度不超过 65,535px 的图像。", exportFailed: "无法导出文件。"
  }
};
