export const translations = {
  en: {
    openFiles: "Open File", openImage: "Open Image", openCtex: "Open CTEX", clearFile: "Clear File", dropFiles: "Drop an image or CTEX", fileName: "Name", format: "Format", fileSize: "Size", resolution: "Resolution", export: "Export File", exportPng: "Export PNG", exportCtex: "Export CTEX", rotateLeft: "↶ Rotate Left", rotateRight: "Rotate Right ↷", zoomIn: "Zoom in", zoomOut: "Zoom out",
    start: "Open an image or supported CTEX file to begin.", imageOnly: "Only PNG or JPEG image files can be opened.", imageRead: "Unable to read the image.", opened: "{name} opened.", cleared: "File cleared.", rotated: "Image rotated {degrees}°.", fileTooSmall: "The file is too small.", notGst2: "This is not a GST2 CTEX file.", unsupportedVersion: "Unsupported CTEX version.", unsupportedCtex: "This is not a WebP-based CTEX file. S3TC and BPTC CTEX are not supported.", invalidResolution: "The CTEX resolution header is invalid.", unsupportedPixelFormat: "Unsupported WebP CTEX pixel format.", invalidPayloadLength: "The CTEX WebP payload length does not match.", invalidWebp: "The CTEX does not contain a valid RIFF/WebP payload.", mismatchedResolution: "The CTEX header and embedded WebP resolution do not match.", webpRead: "Unable to read the embedded WebP image.", pngExported: "PNG exported.", ctexExported: "CTEX exported.", exportFailed: "Unable to export the image.", dimensionLimit: "CTEX export currently supports dimensions up to 65,535px.", webpCreateFailed: "The browser did not create a valid WebP image.", imageCreateFailed: "Unable to create the image."
  },
  ko: {
    openFiles: "파일 열기", openImage: "이미지 열기", openCtex: "CTEX 열기", clearFile: "파일 지우기", dropFiles: "이미지 또는 CTEX 놓기", fileName: "이름", format: "형식", fileSize: "크기", resolution: "해상도", export: "파일 내보내기", exportPng: "PNG 내보내기", exportCtex: "CTEX 내보내기", rotateLeft: "↶ 왼쪽 회전", rotateRight: "오른쪽 회전 ↷", zoomIn: "확대", zoomOut: "축소",
    start: "이미지 또는 지원되는 CTEX 파일을 열어 시작하세요.", imageOnly: "PNG 또는 JPEG 이미지 파일만 열 수 있습니다.", imageRead: "이미지를 읽을 수 없습니다.", opened: "{name} 파일을 열었습니다.", cleared: "파일을 지웠습니다.", rotated: "이미지를 {degrees}° 회전했습니다.", fileTooSmall: "파일이 너무 작습니다.", notGst2: "GST2 CTEX 파일이 아닙니다.", unsupportedVersion: "지원하지 않는 CTEX 버전입니다.", unsupportedCtex: "WebP 기반 CTEX가 아닙니다. S3TC 및 BPTC CTEX는 지원하지 않습니다.", invalidResolution: "CTEX 해상도 헤더가 올바르지 않습니다.", unsupportedPixelFormat: "지원하지 않는 WebP CTEX 픽셀 형식입니다.", invalidPayloadLength: "CTEX WebP 페이로드 길이가 일치하지 않습니다.", invalidWebp: "CTEX에 유효한 RIFF/WebP 페이로드가 없습니다.", mismatchedResolution: "CTEX 헤더와 내장 WebP 해상도가 일치하지 않습니다.", webpRead: "내장 WebP 이미지를 읽을 수 없습니다.", pngExported: "PNG를 내보냈습니다.", ctexExported: "CTEX를 내보냈습니다.", exportFailed: "이미지를 내보낼 수 없습니다.", dimensionLimit: "CTEX 내보내기는 현재 가로·세로 65,535px 이하만 지원합니다.", webpCreateFailed: "브라우저가 유효한 WebP 이미지를 만들지 못했습니다.", imageCreateFailed: "이미지를 만들 수 없습니다."
  },
  ja: {
    openFiles: "ファイルを開く", openImage: "画像を開く", openCtex: "CTEXを開く", clearFile: "ファイルを消去", dropFiles: "画像またはCTEXをドロップ", fileName: "名前", format: "形式", fileSize: "サイズ", resolution: "解像度", export: "ファイルを書き出す", exportPng: "PNGを書き出す", exportCtex: "CTEXを書き出す", rotateLeft: "↶ 左に回転", rotateRight: "右に回転 ↷", zoomIn: "拡大", zoomOut: "縮小",
    start: "画像または対応するCTEXファイルを開いてください。", imageOnly: "PNGまたはJPEG画像ファイルのみ開けます。", imageRead: "画像を読み込めません。", opened: "{name} を開きました。", cleared: "ファイルを消去しました。", rotated: "画像を {degrees}° 回転しました。", fileTooSmall: "ファイルが小さすぎます。", notGst2: "GST2 CTEXファイルではありません。", unsupportedVersion: "対応していないCTEXバージョンです。", unsupportedCtex: "WebPベースのCTEXではありません。S3TCおよびBPTC CTEXには対応していません。", invalidResolution: "CTEX解像度ヘッダーが不正です。", unsupportedPixelFormat: "対応していないWebP CTEXピクセル形式です。", invalidPayloadLength: "CTEX WebPペイロード長が一致しません。", invalidWebp: "CTEXに有効なRIFF/WebPペイロードがありません。", mismatchedResolution: "CTEXヘッダーと埋め込みWebPの解像度が一致しません。", webpRead: "埋め込みWebP画像を読み込めません。", pngExported: "PNGを書き出しました。", ctexExported: "CTEXを書き出しました。", exportFailed: "画像を書き出せません。", dimensionLimit: "CTEXの書き出しは現在65,535px以下の幅・高さのみ対応しています。", webpCreateFailed: "ブラウザが有効なWebP画像を作成できませんでした。", imageCreateFailed: "画像を作成できません。"
  },
  "zh-CN": {
    openFiles: "打开文件", openImage: "打开图像", openCtex: "打开 CTEX", clearFile: "清除文件", dropFiles: "拖放图像或 CTEX", fileName: "名称", format: "格式", fileSize: "大小", resolution: "分辨率", export: "导出文件", exportPng: "导出 PNG", exportCtex: "导出 CTEX", rotateLeft: "↶ 向左旋转", rotateRight: "向右旋转 ↷", zoomIn: "放大", zoomOut: "缩小",
    start: "请打开图像或受支持的 CTEX 文件。", imageOnly: "只能打开 PNG 或 JPEG 图像文件。", imageRead: "无法读取图像。", opened: "已打开 {name}。", cleared: "已清除文件。", rotated: "图像已旋转 {degrees}°。", fileTooSmall: "文件太小。", notGst2: "这不是 GST2 CTEX 文件。", unsupportedVersion: "不支持此 CTEX 版本。", unsupportedCtex: "这不是基于 WebP 的 CTEX 文件。当前不支持 S3TC 和 BPTC CTEX。", invalidResolution: "CTEX 分辨率头无效。", unsupportedPixelFormat: "不支持此 WebP CTEX 像素格式。", invalidPayloadLength: "CTEX WebP 数据长度不匹配。", invalidWebp: "CTEX 不包含有效的 RIFF/WebP 数据。", mismatchedResolution: "CTEX 头与嵌入式 WebP 的分辨率不匹配。", webpRead: "无法读取嵌入式 WebP 图像。", pngExported: "已导出 PNG。", ctexExported: "已导出 CTEX。", exportFailed: "无法导出图像。", dimensionLimit: "CTEX 导出目前仅支持宽度和高度不超过 65,535px 的图像。", webpCreateFailed: "浏览器未能创建有效的 WebP 图像。", imageCreateFailed: "无法创建图像。"
  }
};
